Algoritmo "AreaRetangulo"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Escrever Altura e Largura do Retângulo e descobrir a área
// Autor(a)    : Gabriel Franco Ferreira
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis
  base, altura, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a base: ")
   leia(base)
   escreva("Digite a altura: ")
   leia(altura)
   area <- base * altura
   escreva("A área é: ", area, " metros")

Fimalgoritmo