Algoritmo "exercicio12"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor    : Jailson Costa dos Santos
// Descrição    : Ler temperatura em Fahrenheit, calcular e escrever em Celsius
// Autor(a)     : Gabriel Franco Ferreira
// Data atual   : 30/08/2026
Var
   // Seção de Declarações das variáveis
   f, c : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite a temperatura em Fahrenheit: ")
   Leia(f)
   c <- (f - 32) * 5 / 9
   Escreval("A temperatura em Celsius é: ", c)

Fimalgoritmo