Algoritmo "exercicio23"
// Disciplina   : [Lógica de Programação]
// Professor   Jailson Costas do Santos
// Descrição   : Tendo como dados de entrada o nome, a altura e
//o sexo (M ou F) de uma pessoa, calcule e mostre seu peso ideal,
// utilizando as seguintes fórmulas:
// Autor(a)    : Gabriel Franco Ferreira
// Data atual  : 21/09/2026
Var
   // Seção de Declarações das variáveis


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   // não tem declaração das variáveis
   // não tem entrada de dados
   ler nome // Ler não existe, o comando certo é Leia
   ler sexo
   se sexo = M então//M está sem " para ser reconhecido como
      //caractere
      peso_ideal // Tem um emoji ao invés de <- //
      (72.7 * altura) - 58
   senão //altura em nenhum momento lida ou declarada
      peso_ideal  (62.1 * altura) – 44.7
      fim_se //fimse separado por _
      escrever peso_ideal  // Escreval errado
      fim // Fimalgoritmo errado


Fimalgoritmo