Algoritmo "Antecessor"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler valor do teclado e escrever o antecessor
// Autor(a)    : Gabriel Franco Ferreira
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis
  numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um Numero: ")
Leia(numero)
numero<- numero + 1
Escreva ("O antecessor do seu numero é: ", numero)

Fimalgoritmo