Algoritmo "Exercicio16"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição:  Ler um valor e escrever se é positivo ou negativo
// (considere o valor zero como positivo)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número para saber se é positivo ou negativo")
leia(numero)
se numero < 0 entao
Escreva(numero, " É um Número Negativo!")
senao
Escreva(numero, " É um Número Positivo!")
fimse

Fimalgoritmo