algoritmo "Exercicio15"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costas do Santos
// Descrição    : Lê um número e informa se ele é negativo ou não
// Autor(a)     : Gabriel Franco Ferreira
// Data atual   : 13/09/2026
var
// Seção de Declarações das variáveis
   n: real

inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um número: ")
   Leia(n)

   se (n < 0) entao
      escreval("O número é NEGATIVO")
   senao
      escreval("O número NÃO é negativo")
   fimse

fimalgoritmo