Algoritmo "Exercício14"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE
//10! se o valor lido for maior que 10, caso contrário escrever
//NÃO É MAIOR QUE 10!
// Autor(a)    : Jailson
// Data atual  : 31/08/2026

Var
   // Seção de Declarações das variáveis
   numero : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
    Escreva("Digite um número: ")
    leia(numero)
    se numero > 10 entao
    Escreval("É MAIOR QUE 10 !")
    senao
    Escreval("NÃO É MAIOR QUE 10 !")
    fimse
Fimalgoritmo